apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: raved-dev
data:
  SPRING_PROFILES_ACTIVE: "staging"
  EUREKA_SERVER_URL: "http://eureka-server:8761/eureka/"
  JWT_SECRET: "change_me"
  CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:19006"

