apiVersion: v1
kind: ConfigMap
metadata:
  name: content-service-config
  namespace: raved-dev
data:
  SPRING_PROFILES_ACTIVE: "staging"
  EUREKA_SERVER_URL: "http://eureka-server:8761/eureka/"
  MONGODB_URI: "mongodb://mongodb:27017/raved_content"
  MONGODB_DATABASE: "raved_content"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  ELASTICSEARCH_URIS: "http://elasticsearch:9200"
  KAFKA_SERVERS: "kafka:9092"
  LOG_LEVEL: "INFO"

