apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: raved-dev
data:
  SPRING_PROFILES_ACTIVE: "staging"
  EUREKA_SERVER_URL: "http://eureka-server:8761/eureka/"
  MONGODB_URI: "mongodb://mongodb:27017/raved_notifications"
  MONGODB_DATABASE: "raved_notifications"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  NOTIFICATION_SERVICE_SERVICE_DB_URL: "jdbc:postgresql://postgres:5432/raved_notifications"
  MAIL_FROM: "noreply@raved.app"
  LOG_LEVEL: "INFO"

