apiVersion: v1
kind: ConfigMap
metadata:
  name: social-service-config
  namespace: raved-dev
data:
  SPRING_PROFILES_ACTIVE: "staging"
  EUREKA_SERVER_URL: "http://eureka-server:8761/eureka/"
  SOCIAL_SERVICE_MONGODB_URI: "mongodb://mongodb:27017/raved_social"
  SOCIAL_SERVICE_MONGODB_DATABASE: "raved_social"
  SOCIAL_SERVICE_REDIS_HOST: "redis"
  SOCIAL_SERVICE_REDIS_PORT: "6379"

