nameOverride: analytics-service
image:
  repository: ghcr.io/theravedapp
  tag: prod
service:
  port: 8087
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
ingress:
  enabled: false
resources:
  requests:
    cpu: 300m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi
env:
  - name: SPRING_PROFILES_ACTIVE
    value: production
  - name: MONGODB_URI
    value: ${MONGODB_URI}
secretEnv:
  MONGODB_URI:
    name: raved-mongo
    key: uri

