apiVersion: v1
kind: Service
metadata:
  name: social-service
  namespace: raved-dev
spec:
  selector: { app: social-service }
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
  type: ClusterIP

