workload:
  nameOverride: notification-service
  image:
    repository: ghcr.io/theravedapp
    tag: latest
  service:
    port: 8086
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
  probes:
    liveness:
      path: /actuator/health
      initialDelaySeconds: 60
    readiness:
      path: /actuator/health
      initialDelaySeconds: 20
  envFrom:
    - configMapRef:
        name: common-config
    - configMapRef:
        name: notification-service-config
    - configMapRef:
        name: mongodb-config
    - secretRef:
        name: notification-service-secrets

