nameOverride: config-server
image:
  repository: ghcr.io/theravedapp
  tag: staging
service:
  port: 8888
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
ingress:
  enabled: false
env:
  - name: SPRING_PROFILES_ACTIVE
    value: staging

