{{- if .Values.secrets }}
{{- range $i, $secret := .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{- if $secret.absoluteName }}{{ $secret.name }}{{- else }}{{ include "raved-app.fullname" $ }}-{{ $secret.name }}{{- end }}
type: {{ $secret.type | default "Opaque" }}
 data:
 {{- range $key, $value := $secret.data }}
  {{ $key }}: {{ tpl $value $ | b64enc }}
{{- end }}
---
{{- end }}
{{- end }}


