apiVersion: v1
kind: Service
metadata:
  name: content-service
  namespace: raved-dev
spec:
  selector: { app: content-service }
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
  type: ClusterIP

