apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: raved-dev
spec:
  serviceName: kafka
  selector: { matchLabels: { app: kafka } }
  template:
    metadata:
      labels: { app: kafka }
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:latest
          ports: [{ containerPort: 9092 }]

