apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: raved-dev
spec:
  replicas: 1
  selector:
    matchLabels: { app: analytics-service }
  template:
    metadata:
      labels: { app: analytics-service }
    spec:
      containers:
        - name: analytics-service
          image: raved/analytics-service:latest
          ports:
            - containerPort: 8087
          envFrom:
            - configMapRef:
                name: common-config
            - configMapRef:
                name: analytics-service-config
            - configMapRef:
                name: mongodb-config
            - secretRef:
                name: analytics-service-secrets
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8087
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8087
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            requests:
              cpu: 300m
              memory: 512Mi
            limits:
              cpu: 1200m
              memory: 1536Mi

