package com.raved.analytics.model;

/**
 * EventType Enum for TheRavedApp Analytics
 *
 * Comprehensive categorization of analytics events for tracking user behavior,
 * ecommerce activities, subscription metrics, and system performance.
 */
public enum EventType {
    // User Events
    USER_LOGIN, USER_LOGOUT, USER_REGISTRATION, USER_PROFILE_VIEW, USER_PROFILE_UPDATE,
    USER_PASSWORD_CHANGE, USER_EMAIL_VERIFICATION, USER_PHONE_VERIFICATION,
    USER_ACCOUNT_DELETION, USER_ACCOUNT_SUSPENSION, USER_ACCOUNT_REACTIVATION,

    // Content Events
    POST_VIEW, POST_LIKE, POST_UNLIKE, POST_SHARE, POST_COMMENT, POST_CREATE,
    POST_EDIT, POST_DELETE, POST_REPORT, POST_BOOKMARK, POST_UNBOOKMARK,
    CONTENT_VIEW, CONTENT_LIKE, CONTENT_UNLIKE, CONTENT_SHARE, CONTENT_COMMENT, CONTENT_CREATE,
    CONTENT_EDIT, CONTENT_DELETE, CONTENT_REPORT, CONTENT_BOOKMARK, CONTENT_UNBOOKMARK,
    // E-commerce Events
    PRODUCT_VIEW, PRODUCT_LIKE, PRODUCT_UNLIKE, PRODUCT_PURCHASE, PRODUCT_SEARCH,
    PRODUCT_ADD_TO_CART, PRODUCT_REMOVE_FROM_CART, PRODUCT_ADD_TO_WISHLIST,
    PRODUCT_REMOVE_FROM_WISHLIST, PRODUCT_REVIEW, PRODUCT_RATING,
    CART_ADD, CART_REMOVE, CART_ABANDON, CART_VIEW, CART_UPDATE,
    CHECKOUT_START, CHECKOUT_STEP, CHECKOUT_COMPLETE, CHECKOUT_ABANDON,
    PAYMENT_SUCCESS, PAYMENT_FAILED, PAYMENT_PENDING, PAYMENT_REFUNDED,
    REFUND_REQUESTED, REFUND_PROCESSED, REFUND_DENIED,
    ORDER_PLACED, ORDER_CONFIRMED, ORDER_SHIPPED, ORDER_DELIVERED, ORDER_CANCELLED,
    INVENTORY_UPDATE, PRICE_UPDATE, DISCOUNT_APPLIED, COUPON_APPLIED,
    // Subscription Events
    SUBSCRIPTION_VIEW, SUBSCRIPTION_START, SUBSCRIPTION_RENEWAL, SUBSCRIPTION_CANCELLATION,
    SUBSCRIPTION_UPGRADE, SUBSCRIPTION_DOWNGRADE, SUBSCRIPTION_PAUSE,
    SUBSCRIPTION_RESUME, SUBSCRIPTION_EXPIRED, SUBSCRIPTION_PAYMENT_FAILED,
    SUBSCRIPTION_PAYMENT_SUCCESS, SUBSCRIPTION_TRIAL_START, SUBSCRIPTION_TRIAL_END,
    SUBSCRIPTION_PLAN_CHANGE, SUBSCRIPTION_BILLING_UPDATE, SUBSCRIPTION_REACTIVATION,
    // Chat & Communication Events
    MESSAGE_SENT, MESSAGE_RECEIVED, MESSAGE_READ, MESSAGE_DELETED,
    CHAT_ROOM_JOIN, CHAT_ROOM_LEAVE, CHAT_ROOM_CREATE, CHAT_ROOM_DELETE,
    CHAT_STARTED, CHAT_ENDED, CHAT_INVITATION_SENT, CHAT_INVITATION_ACCEPTED,
    CHAT_INVITATION_DECLINED, CHAT_BLOCK_USER, CHAT_UNBLOCK_USER,
    // Navigation & UI Events
    PAGE_VIEW, PAGE_LOAD, PAGE_UNLOAD, PAGE_ERROR,
    BUTTON_CLICK, LINK_CLICK, FORM_SUBMIT, FORM_VALIDATION_ERROR,
    SEARCH_PERFORMED, SEARCH_RESULT_CLICK, SEARCH_NO_RESULTS,
    FILTER_APPLIED, FILTER_CLEARED, SORT_CHANGED,
    MODAL_OPEN, MODAL_CLOSE, DROPDOWN_OPEN, DROPDOWN_SELECT,
    // Social & Community Events
    GROUP_JOIN, GROUP_LEAVE, GROUP_CREATE, GROUP_DELETE,
    EVENT_RSVP, EVENT_ATTEND, EVENT_CREATE, EVENT_CANCEL,
    POLL_VOTE, POLL_CREATE, POLL_END,
    CHALLENGE_JOIN, CHALLENGE_COMPLETE, CHALLENGE_CREATE,
    // Notification Events
    NOTIFICATION_SENT, NOTIFICATION_RECEIVED, NOTIFICATION_READ,
    NOTIFICATION_DISMISSED, NOTIFICATION_SETTINGS_CHANGED,
    EMAIL_SENT, EMAIL_OPENED, EMAIL_CLICKED, EMAIL_BOUNCED,
    SMS_SENT, SMS_DELIVERED, SMS_FAILED, PUSH_NOTIFICATION_SENT,
    // System & Performance Events
    ERROR_OCCURRED, ERROR_RESOLVED, PERFORMANCE_METRIC,
    API_CALL, API_SUCCESS, API_FAILURE, API_TIMEOUT,
    CACHE_HIT, CACHE_MISS, CACHE_UPDATE, CACHE_CLEAR,
    DATABASE_QUERY, DATABASE_QUERY_SLOW, DATABASE_CONNECTION,
    EXTERNAL_SERVICE_CALL, EXTERNAL_SERVICE_SUCCESS, EXTERNAL_SERVICE_FAILURE,
    // Security Events
    LOGIN_ATTEMPT, LOGIN_FAILURE, LOGIN_SUCCESS, LOGIN_SUSPICIOUS,
    PASSWORD_RESET_REQUESTED, PASSWORD_RESET_COMPLETED,
    TWO_FACTOR_ENABLED, TWO_FACTOR_DISABLED, TWO_FACTOR_VERIFICATION,
    ACCOUNT_LOCKED, ACCOUNT_UNLOCKED, SUSPICIOUS_ACTIVITY_DETECTED,

    // Analytics & Tracking Events
    TRACKING_PIXEL_LOADED, TRACKING_SCRIPT_LOADED,
    A_B_TEST_VIEW, A_B_TEST_CONVERSION, A_B_TEST_VARIANT_ASSIGNED,
    USER_SEGMENT_ASSIGNED, USER_COHORT_ASSIGNED,
    CONVERSION_GOAL_COMPLETED, FUNNEL_STEP_COMPLETED,

    // Mobile App Specific Events
    APP_OPEN, APP_CLOSE, APP_BACKGROUND, APP_FOREGROUND,
    APP_CRASH, APP_PERFORMANCE_ISSUE, APP_UPDATE_AVAILABLE,
    APP_UPDATE_INSTALLED, APP_RATING_REQUESTED, APP_RATING_SUBMITTED,
    PERMISSION_REQUESTED, PERMISSION_GRANTED, PERMISSION_DENIED,

    // Location & Context Events
    LOCATION_ACCESSED, LOCATION_UPDATED, LOCATION_SHARED,
    TIMEZONE_CHANGED, LANGUAGE_CHANGED, CURRENCY_CHANGED,
    DEVICE_ORIENTATION_CHANGED, DEVICE_BATTERY_LOW, DEVICE_STORAGE_LOW,

    // Custom & Business Logic Events
    CUSTOM_EVENT, BUSINESS_RULE_TRIGGERED, WORKFLOW_STARTED,
    WORKFLOW_COMPLETED, WORKFLOW_FAILED, INTEGRATION_TRIGGERED,
    BATCH_PROCESS_STARTED, BATCH_PROCESS_COMPLETED, BATCH_PROCESS_FAILED
}
