nameOverride: events-service
image:
  repository: ghcr.io/theravedapp
  tag: dev
service:
  port: 8088
autoscaling:
  enabled: false
envFrom:
  - configMapRef:
      name: common-config
  - configMapRef:
      name: events-service-config
  - secretRef:
      name: events-service-secrets
probes:
  liveness:
    path: /actuator/health
    initialDelaySeconds: 45
  readiness:
    path: /actuator/health
    initialDelaySeconds: 15

