replicas: 1
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 200m
    memory: 512Mi
elasticsearch:
  hosts:
    - http://elasticsearch-master.raved-dev.svc.cluster.local:9200

