auth:
  username: raved_user
  password: raved_password
  database: raved_dev
primary:
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
persistence:
  enabled: false
service:
  ports:
    postgresql: 5432

