nameOverride: realtime-service
image:
  repository: ghcr.io/theravedapp
  tag: dev
service:
  port: 8084
ingress:
  enabled: false
env:
  - name: SPRING_PROFILES_ACTIVE
    value: local
  - name: RABBITMQ_HOST
    value: rabbitmq.raved-dev.svc.cluster.local
  - name: RABBITMQ_PORT
    value: "5672"

